version: '3.8'
services:
  servicio-Encriptacion-Token:
    build: 
      context: .
      dockerfile: Dockerfile
    image: api-encriptacion-token:v1.0
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 9001"
    environment:
      TZ: "America/Mexico_City"
    restart: always
    network_mode: host